// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using XStats.Core;

#nullable disable

namespace XStats.Core.Migrations
{
    [DbContext(typeof(XStatsContext))]
    partial class XStatsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("AspNetRoles", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "be1e0066-bdee-4ff0-9e10-9ee339e18b59",
                            ConcurrencyStamp = "7f486663-56ac-4c7a-8727-bc1cd210b556",
                            Name = "Admin",
                            NormalizedName = "ADMIN"
                        },
                        new
                        {
                            Id = "096d07a4-5e0b-456e-a533-eeac47b4042b",
                            ConcurrencyStamp = "6bd5b8e5-b260-4962-b1fc-cad03a2beab6",
                            Name = "User",
                            NormalizedName = "USER"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderKey")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);

                    b.HasData(
                        new
                        {
                            UserId = "22eadfb3-a438-4b64-a46d-cc9733a5c509",
                            RoleId = "be1e0066-bdee-4ff0-9e10-9ee339e18b59"
                        },
                        new
                        {
                            UserId = "066c5724-f6b8-49db-be91-88b19e3c3882",
                            RoleId = "be1e0066-bdee-4ff0-9e10-9ee339e18b59"
                        },
                        new
                        {
                            UserId = "066c5724-f6b8-49db-be91-88b19e3c3882",
                            RoleId = "096d07a4-5e0b-456e-a533-eeac47b4042b"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Name")
                        .HasMaxLength(128)
                        .HasColumnType("nvarchar(128)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("XStats.Core.DailyLosses", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("Count")
                        .HasColumnType("int");

                    b.Property<DateTime?>("Date")
                        .HasColumnType("datetime2");

                    b.Property<int?>("TypeId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.ToTable("DailyLosses");
                });

            modelBuilder.Entity("XStats.Core.EquipmentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("FileTitle")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconPath")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("EquipmentTypes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            FileTitle = "aircraft",
                            IconPath = "Images\\eq\\aircraft.png",
                            Order = 1,
                            Title = "Літаки"
                        },
                        new
                        {
                            Id = 2,
                            FileTitle = "helicopter",
                            IconPath = "Images\\eq\\helicopter.png",
                            Order = 2,
                            Title = "Гвинтокрили"
                        },
                        new
                        {
                            Id = 3,
                            FileTitle = "drone",
                            IconPath = "Images\\eq\\drone.png",
                            Order = 3,
                            Title = "Дрони"
                        },
                        new
                        {
                            Id = 4,
                            FileTitle = "anti-aircraft warfare",
                            IconPath = "Images\\eq\\anti-aircraft-warfare.png",
                            Order = 5,
                            Title = "ППО"
                        },
                        new
                        {
                            Id = 5,
                            FileTitle = "cruise missiles",
                            IconPath = "Images\\eq\\cruise-missiles.png",
                            Order = 5,
                            Title = "Крилаті ракети"
                        },
                        new
                        {
                            Id = 6,
                            FileTitle = "tank",
                            IconPath = "Images\\eq\\tank.png",
                            Order = 6,
                            Title = "Танки"
                        },
                        new
                        {
                            Id = 7,
                            FileTitle = "APC",
                            IconPath = "Images\\eq\\apc.png",
                            Order = 7,
                            Title = "БТР"
                        },
                        new
                        {
                            Id = 8,
                            FileTitle = "field artillery",
                            IconPath = "Images\\eq\\field-artillery.png",
                            Order = 8,
                            Title = "Артилерія"
                        },
                        new
                        {
                            Id = 9,
                            FileTitle = "MLP",
                            IconPath = "Images\\eq\\mlr.png",
                            Order = 9,
                            Title = "РСЗВ"
                        },
                        new
                        {
                            Id = 10,
                            FileTitle = "vehicles and fuel tanks",
                            IconPath = "Images\\eq\\vehicles-and-fuel-tanks.png",
                            Order = 10,
                            Title = "Техніка і цистерни з ПММ"
                        },
                        new
                        {
                            Id = 11,
                            FileTitle = "naval ship",
                            IconPath = "Images\\eq\\naval-ship.png",
                            Order = 11,
                            Title = "Морські кораблі"
                        },
                        new
                        {
                            Id = 12,
                            FileTitle = "special equipment",
                            IconPath = "Images\\eq\\special-equipment.png",
                            Order = 12,
                            Title = "Спец. обладнання"
                        });
                });

            modelBuilder.Entity("XStats.Core.User", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("AspNetUsers", (string)null);

                    b.HasData(
                        new
                        {
                            Id = "22eadfb3-a438-4b64-a46d-cc9733a5c509",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "21b635df-ae65-40fc-8975-16f5a7c20483",
                            Email = "admin@xstats.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "ADMIN@XSTATS.COM",
                            NormalizedUserName = "ADMIN@XSTATS.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAEJW+Zfezu3VLXFK2hSrVpWl0p7mrsTKlWs6qwjj27jpa2Csx0184k+pg3YuicegxJQ==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "33df2cbe-0eb8-46ff-b262-f2089c3056df",
                            TwoFactorEnabled = false,
                            UserName = "admin@xstats.com"
                        },
                        new
                        {
                            Id = "066c5724-f6b8-49db-be91-88b19e3c3882",
                            AccessFailedCount = 0,
                            ConcurrencyStamp = "d9253c26-6229-4426-8704-0898dc4da27d",
                            Email = "user@xstats.com",
                            EmailConfirmed = true,
                            LockoutEnabled = false,
                            NormalizedEmail = "USER@XSTATS.COM",
                            NormalizedUserName = "USER@XSTATS.COM",
                            PasswordHash = "AQAAAAEAACcQAAAAELM14SEP09WsMQNCxQdHiNJ2rF+rkW2DB78/HXYKaLJoVaozGnt2Fk1cvzuk/POysw==",
                            PhoneNumberConfirmed = false,
                            SecurityStamp = "b1d79bf4-fe83-4ed6-be4c-20052f830444",
                            TwoFactorEnabled = false,
                            UserName = "user@xstats.com"
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("XStats.Core.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("XStats.Core.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("XStats.Core.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("XStats.Core.User", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("XStats.Core.DailyLosses", b =>
                {
                    b.HasOne("XStats.Core.EquipmentType", "Type")
                        .WithMany("Losses")
                        .HasForeignKey("TypeId");

                    b.Navigation("Type");
                });

            modelBuilder.Entity("XStats.Core.EquipmentType", b =>
                {
                    b.Navigation("Losses");
                });
#pragma warning restore 612, 618
        }
    }
}
